[project]
name = "mnist-cvnn-jax-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.9.0",
    "numpy>=2.4.2",
    "optax>=0.2.6",
    "tensorflow>=2.20.0",
    "tensorflow-datasets>=4.9.9",
]
